// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyPlanner.API.Data;

#nullable disable

namespace VolleyPlanner.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005103705_TournamentModuleInitial")]
    partial class TournamentModuleInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VolleyPlanner.API.Entities.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainingSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("UserId", "TrainingSessionId")
                        .IsUnique()
                        .HasFilter("[TrainingSessionId] IS NOT NULL");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int>("SportType")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.ExerciseTag", b =>
                {
                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ExerciseTags");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.GenerationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMin")
                        .HasColumnType("int");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryFocus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GenerationRequests");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Player1UserId")
                        .HasColumnType("int");

                    b.Property<int>("Player2UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Player1UserId");

                    b.HasIndex("Player2UserId");

                    b.ToTable("Teams", t =>
                        {
                            t.HasCheckConstraint("CK_Team_DifferentPlayers", "[Player1UserId] <> [Player2UserId]");
                        });
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TeamInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvitedUserId")
                        .HasColumnType("int");

                    b.Property<int>("InviterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TeamInvitations");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxTeams")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizerUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId", "TeamId")
                        .IsUnique();

                    b.ToTable("TournamentEntries");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAutomaticResult")
                        .HasColumnType("bit");

                    b.Property<int?>("LoserEntryId")
                        .HasColumnType("int");

                    b.Property<int>("MatchNumber")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("Team1EntryId")
                        .HasColumnType("int");

                    b.Property<int?>("Team1SetsWon")
                        .HasColumnType("int");

                    b.Property<int?>("Team1SourceMatchId")
                        .HasColumnType("int");

                    b.Property<int>("Team1SourceType")
                        .HasColumnType("int");

                    b.Property<int?>("Team2EntryId")
                        .HasColumnType("int");

                    b.Property<int?>("Team2SetsWon")
                        .HasColumnType("int");

                    b.Property<int?>("Team2SourceMatchId")
                        .HasColumnType("int");

                    b.Property<int>("Team2SourceType")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentPoolId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoserEntryId");

                    b.HasIndex("Team1EntryId");

                    b.HasIndex("Team1SourceMatchId");

                    b.HasIndex("Team2EntryId");

                    b.HasIndex("Team2SourceMatchId");

                    b.HasIndex("TournamentPoolId");

                    b.HasIndex("WinnerEntryId");

                    b.HasIndex("TournamentId", "MatchNumber")
                        .IsUnique();

                    b.ToTable("TournamentMatches");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentMatchSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<int>("Team1Points")
                        .HasColumnType("int");

                    b.Property<int>("Team2Points")
                        .HasColumnType("int");

                    b.Property<int>("TournamentMatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentMatchId", "SetNumber")
                        .IsUnique();

                    b.ToTable("TournamentMatchSets");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoolNumber")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "PoolNumber")
                        .IsUnique();

                    b.ToTable("TournamentPools");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentPoolSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FinalRank")
                        .HasColumnType("int");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentEntryId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentPoolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentEntryId");

                    b.HasIndex("TournamentPoolId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("TournamentPoolSlots");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TrainingSessionId", "UserId")
                        .IsUnique();

                    b.ToTable("TrainingBookings");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryFocus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SportType")
                        .HasColumnType("int");

                    b.Property<int>("TargetDuration")
                        .HasColumnType("int");

                    b.Property<string>("TargetIntensity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TrainingPlans");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PlannedDuration")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingPlanItems");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<int>("OrganizerUserId")
                        .HasColumnType("int");

                    b.Property<int>("SportType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainingPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PlayerCode")
                        .IsUnique()
                        .HasFilter("[PlayerCode] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Goal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.UserSportRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleType")
                        .IsUnique();

                    b.ToTable("UserSportRoles");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.CalendarEvent", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyPlanner.API.Entities.TrainingSession", "TrainingSession")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TrainingPlan");

                    b.Navigation("TrainingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.ExerciseTag", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.Exercise", "Exercise")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.Tag", "Tag")
                        .WithMany("ExerciseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.GenerationRequest", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithMany("GenerationRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Team", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "Player1User")
                        .WithMany("TeamsAsPlayer1")
                        .HasForeignKey("Player1UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.User", "Player2User")
                        .WithMany("TeamsAsPlayer2")
                        .HasForeignKey("Player2UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Player1User");

                    b.Navigation("Player2User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TeamInvitation", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "InvitedUser")
                        .WithMany("ReceivedTeamInvitations")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.User", "InviterUser")
                        .WithMany("SentTeamInvitations")
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.Tournament", "Tournament")
                        .WithMany("TeamInvitations")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedUser");

                    b.Navigation("InviterUser");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Tournament", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "OrganizerUser")
                        .WithMany("OrganizedTournaments")
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OrganizerUser");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentEntry", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.Team", "Team")
                        .WithMany("TournamentEntries")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.Tournament", "Tournament")
                        .WithMany("Entries")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentMatch", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.TournamentEntry", "LoserEntry")
                        .WithMany()
                        .HasForeignKey("LoserEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentEntry", "Team1Entry")
                        .WithMany("MatchesAsTeam1")
                        .HasForeignKey("Team1EntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentMatch", "Team1SourceMatch")
                        .WithMany()
                        .HasForeignKey("Team1SourceMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentEntry", "Team2Entry")
                        .WithMany("MatchesAsTeam2")
                        .HasForeignKey("Team2EntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentMatch", "Team2SourceMatch")
                        .WithMany()
                        .HasForeignKey("Team2SourceMatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.TournamentPool", "TournamentPool")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentPoolId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentEntry", "WinnerEntry")
                        .WithMany()
                        .HasForeignKey("WinnerEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LoserEntry");

                    b.Navigation("Team1Entry");

                    b.Navigation("Team1SourceMatch");

                    b.Navigation("Team2Entry");

                    b.Navigation("Team2SourceMatch");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentPool");

                    b.Navigation("WinnerEntry");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentMatchSet", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.TournamentMatch", "TournamentMatch")
                        .WithMany("Sets")
                        .HasForeignKey("TournamentMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentMatch");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentPool", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.Tournament", "Tournament")
                        .WithMany("Pools")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentPoolSlot", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.TournamentEntry", "TournamentEntry")
                        .WithMany("PoolSlots")
                        .HasForeignKey("TournamentEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VolleyPlanner.API.Entities.TournamentPool", "TournamentPool")
                        .WithMany("Slots")
                        .HasForeignKey("TournamentPoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TournamentEntry");

                    b.Navigation("TournamentPool");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingBooking", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Bookings")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithMany("TrainingBookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TrainingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingPlan", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithMany("TrainingPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingPlanItem", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("Items")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingSession", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "OrganizerUser")
                        .WithMany("OrganizedTrainingSessions")
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("VolleyPlanner.API.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrganizerUser");

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.UserProfile", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("VolleyPlanner.API.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.UserSportRole", b =>
                {
                    b.HasOne("VolleyPlanner.API.Entities.User", "User")
                        .WithMany("SportRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Exercise", b =>
                {
                    b.Navigation("ExerciseTags");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Tag", b =>
                {
                    b.Navigation("ExerciseTags");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Team", b =>
                {
                    b.Navigation("TournamentEntries");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.Tournament", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Matches");

                    b.Navigation("Pools");

                    b.Navigation("TeamInvitations");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentEntry", b =>
                {
                    b.Navigation("MatchesAsTeam1");

                    b.Navigation("MatchesAsTeam2");

                    b.Navigation("PoolSlots");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentMatch", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TournamentPool", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingPlan", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("Items");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.TrainingSession", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CalendarEvents");
                });

            modelBuilder.Entity("VolleyPlanner.API.Entities.User", b =>
                {
                    b.Navigation("CalendarEvents");

                    b.Navigation("GenerationRequests");

                    b.Navigation("OrganizedTournaments");

                    b.Navigation("OrganizedTrainingSessions");

                    b.Navigation("Profile");

                    b.Navigation("ReceivedTeamInvitations");

                    b.Navigation("SentTeamInvitations");

                    b.Navigation("SportRoles");

                    b.Navigation("TeamsAsPlayer1");

                    b.Navigation("TeamsAsPlayer2");

                    b.Navigation("TrainingBookings");

                    b.Navigation("TrainingPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
